
import '../data/vos/movie_seat_vo.dart';
import 'package:movie_booking_app/resources/strings.dart';

List<MovieSeatVO> dummyMovieSeats = [
  MovieSeatVO("A", SEAT_TYPE_TEXT),
  MovieSeatVO("", SEAT_TYPE_EMPTY),
  MovieSeatVO("", SEAT_TYPE_AVAILABLE),
  MovieSeatVO("", SEAT_TYPE_AVAILABLE),
  MovieSeatVO("", SEAT_TYPE_AVAILABLE),
  MovieSeatVO("", SEAT_TYPE_AVAILABLE),
  MovieSeatVO("", SEAT_TYPE_AVAILABLE),
  MovieSeatVO("", SEAT_TYPE_AVAILABLE),
  MovieSeatVO("", SEAT_TYPE_EMPTY),
  MovieSeatVO("A", SEAT_TYPE_TEXT),

  MovieSeatVO("B", SEAT_TYPE_TEXT),
  MovieSeatVO("", SEAT_TYPE_AVAILABLE),
  MovieSeatVO("", SEAT_TYPE_AVAILABLE),
  MovieSeatVO("", SEAT_TYPE_AVAILABLE),
  MovieSeatVO("", SEAT_TYPE_AVAILABLE),
  MovieSeatVO("", SEAT_TYPE_AVAILABLE),
  MovieSeatVO("", SEAT_TYPE_AVAILABLE),
  MovieSeatVO("", SEAT_TYPE_AVAILABLE),
  MovieSeatVO("", SEAT_TYPE_AVAILABLE),
  MovieSeatVO("B", SEAT_TYPE_TEXT),

  MovieSeatVO("C", SEAT_TYPE_TEXT),
  MovieSeatVO("", SEAT_TYPE_AVAILABLE),
  MovieSeatVO("", SEAT_TYPE_AVAILABLE),
  MovieSeatVO("", SEAT_TYPE_AVAILABLE),
  MovieSeatVO("", SEAT_TYPE_AVAILABLE),
  MovieSeatVO("", SEAT_TYPE_AVAILABLE),
  MovieSeatVO("", SEAT_TYPE_AVAILABLE),
  MovieSeatVO("", SEAT_TYPE_AVAILABLE),
  MovieSeatVO("", SEAT_TYPE_AVAILABLE),
  MovieSeatVO("C", SEAT_TYPE_TEXT),

  MovieSeatVO("D", SEAT_TYPE_TEXT),
  MovieSeatVO("", SEAT_TYPE_AVAILABLE),
  MovieSeatVO("", SEAT_TYPE_AVAILABLE),
  MovieSeatVO("", SEAT_TYPE_AVAILABLE),
  MovieSeatVO("", SEAT_TYPE_AVAILABLE),
  MovieSeatVO("", SEAT_TYPE_AVAILABLE),
  MovieSeatVO("", SEAT_TYPE_AVAILABLE),
  MovieSeatVO("", SEAT_TYPE_AVAILABLE),
  MovieSeatVO("", SEAT_TYPE_AVAILABLE),
  MovieSeatVO("D", SEAT_TYPE_TEXT),

  MovieSeatVO("E", SEAT_TYPE_TEXT),
  MovieSeatVO("", SEAT_TYPE_AVAILABLE),
  MovieSeatVO("", SEAT_TYPE_TAKEN),
  MovieSeatVO("", SEAT_TYPE_TAKEN),
  MovieSeatVO("", SEAT_TYPE_TAKEN),
  MovieSeatVO("", SEAT_TYPE_AVAILABLE),
  MovieSeatVO("", SEAT_TYPE_AVAILABLE),
  MovieSeatVO("", SEAT_TYPE_AVAILABLE),
  MovieSeatVO("", SEAT_TYPE_AVAILABLE),
  MovieSeatVO("E", SEAT_TYPE_TEXT),

  MovieSeatVO("F", SEAT_TYPE_TEXT),
  MovieSeatVO("", SEAT_TYPE_AVAILABLE),
  MovieSeatVO("", SEAT_TYPE_AVAILABLE),
  MovieSeatVO("", SEAT_TYPE_AVAILABLE),
  MovieSeatVO("", SEAT_TYPE_AVAILABLE),
  MovieSeatVO("", SEAT_TYPE_AVAILABLE),
  MovieSeatVO("", SEAT_TYPE_AVAILABLE),
  MovieSeatVO("", SEAT_TYPE_AVAILABLE),
  MovieSeatVO("", SEAT_TYPE_AVAILABLE),
  MovieSeatVO("F", SEAT_TYPE_TEXT),

  MovieSeatVO("G", SEAT_TYPE_TEXT),
  MovieSeatVO("", SEAT_TYPE_AVAILABLE),
  MovieSeatVO("", SEAT_TYPE_AVAILABLE),
  MovieSeatVO("", SEAT_TYPE_AVAILABLE),
  MovieSeatVO("", SEAT_TYPE_AVAILABLE),
  MovieSeatVO("", SEAT_TYPE_AVAILABLE),
  MovieSeatVO("", SEAT_TYPE_AVAILABLE),
  MovieSeatVO("", SEAT_TYPE_AVAILABLE),
  MovieSeatVO("", SEAT_TYPE_AVAILABLE),
  MovieSeatVO("G", SEAT_TYPE_TEXT),

];